# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(734, 550)
        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralWidget)
        self.verticalLayout.setContentsMargins(11, 11, 9, 9)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_repo_path = QtWidgets.QLabel(self.centralWidget)
        self.label_repo_path.setObjectName("label_repo_path")
        self.horizontalLayout.addWidget(self.label_repo_path)
        self.line_edit_repo_path = QtWidgets.QLineEdit(self.centralWidget)
        self.line_edit_repo_path.setObjectName("line_edit_repo_path")
        self.horizontalLayout.addWidget(self.line_edit_repo_path)
        self.button_select_repo_path = QtWidgets.QPushButton(self.centralWidget)
        self.button_select_repo_path.setObjectName("button_select_repo_path")
        self.horizontalLayout.addWidget(self.button_select_repo_path)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(11, 11, 11, 11)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_group_type = QtWidgets.QLabel(self.centralWidget)
        self.label_group_type.setObjectName("label_group_type")
        self.horizontalLayout_2.addWidget(self.label_group_type)
        self.group_type_combobox = QtWidgets.QComboBox(self.centralWidget)
        self.group_type_combobox.setObjectName("group_type_combobox")
        self.horizontalLayout_2.addWidget(self.group_type_combobox)
        self.label_day = QtWidgets.QLabel(self.centralWidget)
        self.label_day.setObjectName("label_day")
        self.horizontalLayout_2.addWidget(self.label_day)
        self.group_day_combobox = QtWidgets.QComboBox(self.centralWidget)
        self.group_day_combobox.setObjectName("group_day_combobox")
        self.horizontalLayout_2.addWidget(self.group_day_combobox)
        self.label_group = QtWidgets.QLabel(self.centralWidget)
        self.label_group.setObjectName("label_group")
        self.horizontalLayout_2.addWidget(self.label_group)
        self.group_combobox = QtWidgets.QComboBox(self.centralWidget)
        self.group_combobox.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.group_combobox.setObjectName("group_combobox")
        self.horizontalLayout_2.addWidget(self.group_combobox)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.table_widget = QtWidgets.QTableWidget(self.centralWidget)
        self.table_widget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.table_widget.setObjectName("table_widget")
        self.table_widget.setColumnCount(0)
        self.table_widget.setRowCount(0)
        self.table_widget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.table_widget)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(11, 11, 11, 11)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.console = QtWidgets.QLineEdit(self.centralWidget)
        self.console.setObjectName("console")
        self.gridLayout.addWidget(self.console, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.console_output = QtWidgets.QLabel(self.centralWidget)
        self.console_output.setText("")
        self.console_output.setObjectName("console_output")
        self.gridLayout.addWidget(self.console_output, 0, 0, 1, 2)
        self.verticalLayout.addLayout(self.gridLayout)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 100)
        self.verticalLayout.setStretch(3, 2)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 734, 27))
        self.menuBar.setObjectName("menuBar")
        MainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.action_export = QtWidgets.QAction(MainWindow)
        self.action_export.setObjectName("action_export")
        self.action_new = QtWidgets.QAction(MainWindow)
        self.action_new.setObjectName("action_new")
        self.action_undo = QtWidgets.QAction(MainWindow)
        self.action_undo.setObjectName("action_undo")
        self.action_redo = QtWidgets.QAction(MainWindow)
        self.action_redo.setObjectName("action_redo")
        self.action_add_student = QtWidgets.QAction(MainWindow)
        self.action_add_student.setObjectName("action_add_student")
        self.toolBar.addAction(self.action_new)
        self.toolBar.addAction(self.action_export)
        self.toolBar.addAction(self.action_undo)
        self.toolBar.addAction(self.action_redo)
        self.toolBar.addAction(self.action_add_student)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PK Übungstool"))
        self.label_repo_path.setText(_translate("MainWindow", "Pfad zum PK-Repo:"))
        self.button_select_repo_path.setText(_translate("MainWindow", "Auswählen"))
        self.label_group_type.setText(_translate("MainWindow", "Gruppentype:"))
        self.label_day.setText(_translate("MainWindow", "Übungstag:"))
        self.label_group.setText(_translate("MainWindow", "Gruppe:"))
        self.table_widget.setSortingEnabled(True)
        self.label_2.setText(_translate("MainWindow", "Befehl: "))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.action_export.setText(_translate("MainWindow", "Exportieren"))
        self.action_new.setText(_translate("MainWindow", "Neu"))
        self.action_new.setToolTip(_translate("MainWindow", "Neu"))
        self.action_undo.setText(_translate("MainWindow", "Zurück"))
        self.action_redo.setText(_translate("MainWindow", "Vor"))
        self.action_add_student.setText(_translate("MainWindow", "Student hinzufügen"))

